# Generated by Django 5.0.3 on 2024-03-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='Todo',
        ),
    ]
